// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.com.wangzunbin.proto

package com.wangzunbin.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shengsiyuan.com.wangzunbin.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
